version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: participa_df
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: senha_forte
    ports:
      # MUDANÇA CRÍTICA: Vamos usar a porta 5433 externamente para fugir de conflitos
      - "5433:5432"
    volumes:
      # MUDANÇA CRÍTICA: Mudamos o nome do volume para forçar um banco zero km
      - pg_data_novo:/var/lib/postgresql/data

  backend:
    build:
      context: ./participa-DF-Back
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      # Internamente no Docker, eles continuam se falando na porta padrão 5432
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: senha_forte
      DB_NAME: participa_df
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./participa-DF-Back
          target: /app
        - action: rebuild
          path: ./participa-DF-Back/package.json

  frontend:
    build:
      context: ./participa-DF-Front/web
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./participa-DF-Front/web
          target: /app
        - action: rebuild
          path: ./participa-DF-Front/web/package.json

volumes:
  pg_data_novo: # Volume novo